name: CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: |
        cargo build
    - name: Run tests
      run: |
        cargo test

        sudo apt-get -y update
        sudo apt-get -y install bubblewrap fuse-overlayfs libseccomp-dev nftables podman slirp4netns
        bwrap --version
        fuse-overlayfs --version
        nft --version
        podman --version
        slirp4netns --version
        sh tests/tests.sh
