name: CI

on:
  push:
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        sudo apt-get -y update
        sudo apt-get -y install bubblewrap fuse-overlayfs libseccomp-dev nftables podman slirp4netns

    - name: Build
      run: |
        cargo build

    - name: Run tests
      run: |
        cargo test

        uname -a
        bwrap --version
        fuse-overlayfs --version
        nft --version
        podman --version
        slirp4netns --version

        # Workaround for https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=2b5f9dad32ed19e8db3b0f10a84aa824a219803b
        KEG_BASE_TEST_ARGS="--share-time" \
        KEG_ROOTFS_TEST_ARGS="--share-time" \
        KEG_TEST_ARGS="--share-time" \
        KEG_HOME_TEST_ARGS="--share-time" \
        sh tests/tests.sh

    - name: Publish package
      if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/')
      env:
        CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
      run: |
        cargo publish
